name: Pull Request Automation
 
on:
  pull_request:
    types: [closed]
    branches:
      - master
 
jobs:
  process_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Fetch master branch
        run: git fetch origin master
 
      - name: Check if from QA to Master
        if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'qa' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ github.event.pull_request.title }}" -m "${{ github.event.pull_request.body }}"
          git push origin "${{ github.event.pull_request.title }}"

      - name: Check if from hotfixes to Master
        if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'hotfixes' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ github.event.pull_request.title }}" -m "${{ github.event.pull_request.body }}"
          git push origin "${{ github.event.pull_request.title }}"

      - name: Check if from Dev to QA
        if: ${{ github.event.pull_request.base.ref == 'qa' && github.event.pull_request.head.ref == 'dev' }}
        run: |
          echo "No action required for PR from Dev to QA"
